### ISSUE TITLE
No Autofocus with Sketch 53

### ISSUE THREAD

**Issue by phytrisha** [ANGIstudio/Sketch-Resize-Commands#5]
Since Sketch 53, the input field isn't focussed automatically when opening via shortcut. Would love to see this fixed again!

Thanks!

**Comment by andrejilderda** [comment]
Hi @phytrisha, thanks! I resolved this in the new version. Can you please check if that is the case for you?

Cheers,
Andre

**Comment by phytrisha** [comment]
Works perfectly, both issues! Thanks for the quick fix!

Cheers,
Mark
